version: '3.9'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    hostname: frontend
    environment:
     - BACKEND_URL=http://backend:5000/submit
    ports:
      - "3000:3000"
    networks:
      - customnet
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    hostname: backend
    ports:
      - "5000:5000"
    networks:
      - customnet

networks:
  customnet:
    driver: bridge
